version: "3.10.4"
services:
  management_service:
    image: kjosbakken/payed_book_api:test
    ports:
      - 5000:5000
    extra_hosts:
      mongoservice: 172.17.0.1
    networks:
      - backend
  db_service:
    image: kjosbakken/mongo:latest
    ports:
      - 27017:27017
    extra_hosts:
      mongoservice: 172.17.0.1
    networks:
      - backend
    
networks:
  backend:
    driver: bridge
